# Generated by Django 3.0.7 on 2021-03-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
